version: '3.8'

services:
  mysql_test:
    image: mysql:8.0
    container_name: myapi_mysql_test
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "test_db"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "secret"
    ports:
      - "33060:3306" # map container 3306 to host 33060 to avoid collisions
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s
    volumes:
      - mysql_test_data:/var/lib/mysql

volumes:
  mysql_test_data:
    driver: local
